# Generated by Django 4.2.2 on 2023-06-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionformmodel',
            name='is_hostellite',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
