# Generated by Django 4.2.2 on 2023-07-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationformmodel',
            old_name='aadhar_card',
            new_name='aadhaar_card',
        ),
    ]
