# Generated by Django 4.2.2 on 2023-07-07 18:49

import FormApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0003_applicationformmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformmodel',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='allotment_order_sslc_certificate',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='anti_ragging_bond',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='community_certificate',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='conduct_certificate',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='declaration_form',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='eligibility_migration_certificates',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='hsc_certificate',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='nativity_certificate',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='neet_admit_card',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='neet_score_card',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='physical_fitness_certificate',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='physically_handicapped_certificate',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to=FormApp.models.image_path_and_rename),
        ),
        migrations.AlterField(
            model_name='applicationformmodel',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to=FormApp.models.pdf_path_and_rename),
        ),
    ]
